#!/bin/bash

USER=$(id -u)

if [ $USER -eq 0 ]
then 
 echo "You are installing packages with root access"
else
 echo "Please run the script with root access"
 exit 1
fi 

echo "checking is package already installed are not"

dnf list installed nginx1234

if [ $? -eq 0 ]
then
 echo "Package already installed"
else
 echo "Package was not installed going to install"
 dnf install nginx -y
 if [ $? -eq 0 ]
 then 
  echo "package installation was successfull"
 else
  echo "package installation was not successfull"
  exit 1
 fi
fi
